config/routes.rb
Rails.application.routes.draw do
  resources :complaints do
    get 'handle'
    post 'do_handle'
  end
  root :to => 'commodities#index'

  resources :sellers do
    resources :shops
  end

  resources :commodities do
    resources :sections do
      resources :comments do
        get 'reply'
        post 'do_reply'
      end
    end
    collection do
      post 'do_filter'
    end
  end

  resources :categories
  resources :admins
  resources :customers do
    resources :orders do
      post 'purchase'
    end
    resources :records
  end
  resources :accounts do
    collection do
      get 'login'
      post 'do_login'
      get 'logout'
      get 'register'
      post 'do_register'
    end
    get 'top_up'
    post 'do_top_up'
    get 'statistic'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_one :admin, dependent: :destroy
  has_one :seller, dependent: :destroy
  has_one :customer, dependent: :destroy
  validates :name, :password, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :account, dependent: :destroy
  has_many :complaints, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :commodities
  has_one_attached :image, dependent: :destroy
  validates :image, attached: true, content_type: [:jpg, :png, :jpeg], size: { less_than: 5.megabytes }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :account
  belongs_to :section
  belongs_to :comment
  has_many :comments
  validates :content, presence: true

  def destroy
    comments.filter { |c| c != self }.each { |c| c.destroy }
    super
  end
end

app/models/commodity.rb
class Commodity < ApplicationRecord
  belongs_to :shop
  has_and_belongs_to_many :categories, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :name, :price, :introduction, presence: true
  validates :image, attached: true, content_type: [:jpg, :png, :jpeg], size: { less_than: 5.megabytes }
  scope :filter_by_categories, -> (cset) {
    reject { |c|
      (c.category_ids.map(&:to_i) & cset.reject(&:blank?).map(&:to_i)).empty?
    }
  }

  def sections
    Section.all.filter { |s| s.commodity == self }
  end

  def sales_volume
    Order.all.filter { |o| o.commodity == self && o.done }.map { |o| o.count }.reduce { |x, y| x + y } || 0
  end
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :customer
  belongs_to :seller
  belongs_to :admin, :optional => true
  validates :content, presence: true

  def is_handled?
    not self.admin.nil?
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :account
  has_many :orders, dependent: :destroy
  has_many :complaints, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :commodity
  belongs_to :customer
  has_one :record, dependent: :destroy
  validates :count, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :order
  has_one :section, dependent: :destroy
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :record
  has_many :comments, dependent: :destroy
  validates :grade, presence: true

  def commodity
    record.order.commodity
  end
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :account
  has_many :complaints, dependent: :destroy
  has_many :shops, dependent: :destroy
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :seller
  has_many :commodities, dependent: :destroy
  validates :name, :introduction, presence: true
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]
  before_action :authenticate, only: [:update, :destroy]
  before_action :ban, only: [:index]

  def authenticate
    redirect_to login_accounts_url, alert: "您必须以管理员或商铺所有者身份登录！" unless current_admin? ||
      (current_seller? && current_account.seller.shops.exists? { |s| s == @shop })
  end

  def ban
    redirect_to root_url, notice: "非法操作"
  end

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @seller = Seller.find(params[:seller_id])
    @shop = Shop.new(shop_params)
    @shop.seller = @seller

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @seller, notice: "成功创建店铺！" }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render "shops/new", status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      @seller = Seller.find(params[:seller_id])
      if @shop.update(shop_params)
        format.html { redirect_to @seller, notice: "成功更新店铺！" }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render "shops/edit", status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to seller_url(Seller.find(@shop.seller_id)), notice: "成功删除店铺！" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :introduction, :seller_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_edit_form.html.erb
<%= form_with(model: shop, url: url, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-dark">当前用户： <%= current_account.name %></div>
  <li class="dropdown-divider "></li>

  <div class="center" style="width: 50%; margin: auto;">
    <div class="field">
      <div class="text-dark labelLine">商店名称<br>
        <%= form.text_field :name, required:"",style:"width: 100%" %>
      </div>
    </div>

    <div class="field">
      <div class="text-dark labelLine">商店介绍<br>
        <%= form.text_area :introduction ,style:"width: 100%" %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary leftButton", value: "编辑商店", data: { disable_with: "正在编辑商店" } %>
      <%= link_to '返回', seller_shop_path(@shop.seller), class: "btn btn-primary rightButton", style: "color: gainsboro" %>
    </div>
  </div>
<% end %>

app/views/shops/_form.html.erb
<%= form_with(model: shop, url: url, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div id="shop_<%= shop.id %>">
  <p>
    Name: <strong><%= shop.name %></strong><br/>
    Introduction: <%= shop.introduction %>
  </p>
  <%= link_to 'Details', seller_shop_url(@seller, shop) %> |
  <%= link_to 'Destroy', seller_shop_url(@seller, shop), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/shops/edit.html.erb
<h1 class="text-center">编辑商店</h1>

<div class="card orderCard">
  <div class="card-header">商店信息</div>
  <div class="card-body">
    <%= render 'edit_form', shop: @shop, url: seller_shop_url(@shop.seller) %>
  </div>
</div>

app/views/shops/index.html.erb
<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Introduction</th>
      <th>Seller</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.introduction %></td>
        <td><%= shop.seller.account.name %></td>
        <td><%= link_to 'Show', seller_shop_url(shop.seller, shop) %></td>
        <% if current_account && current_account.id == shop.seller.account.id %>
          <td><%= link_to 'Edit', edit_seller_shop_url(shop.seller, shop) %></td>
          <td><%= link_to 'Destroy', seller_shop_url(shop.seller, shop), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<div>
  <div class="card" style="width:40%">
    <div class="card-header" style="font-size: 100%">店铺信息</div>
    <div class="card-body">
      <p class="card-text">店名：<%= @shop.name %></p>
      <p class="card-text">简介：<%= @shop.introduction %></p>
      <p class="card-text">店主：<%= @shop.seller.account.name %></p>
      <p class="card-text">ID：<%= @shop.seller.account.id %></p>
      <% if current_account && current_account.id == @shop.seller.account.id %>
        <%= link_to '编辑', edit_seller_shop_path(@shop.seller, @shop), class: 'btn btn-primary', style: "color: gainsboro; width: 20%" %>
      <% end %>
    </div>
  </div>
  <br>
</div>


<div class="content">  
  <div class="proRow">
      <% @shop.commodities.each do |commodity| %>
          <div class="proBig">
              <div class="pro">
                  <div class="proImg">
                    <% if commodity.image.attached? %>
                      <image src="<%= url_for commodity.image %>"></image>
                    <% end %>
                  </div>
                  <div class="proText">
                      <h5 class="h5Commodity"><%= commodity.name %></h5>
                      <p class = "proIntro"><%= commodity.introduction %></p>
                      <p class = "proPrice"><%= commodity.price %> RMB</p>
                      <p class = "proFrom"><%= commodity.shop.name %></p>
                      <p class = "proCatagory"><%= commodity.categories.collect { |c| c.name }.reduce { |x, y| x + ", " + y } %></p>
                  </div>
              </div>
              <a href="#">
                  <div class="proBtn">
                  	  <%= link_to '查看', commodity, class:'btn btn-primary btnCommodity', style: "color: gainsboro"%>
                      <% if current_account && current_account.id == commodity.shop.seller.account.id %>
                        <%= link_to '编辑', edit_commodity_path(commodity), class:'btn btn-primary btnCommodity', style: "color: gainsboro"%>
                        <%= link_to '删除', commodity, class:'btn btn-primary btnCommodity', style: "color: gainsboro",  method: :delete, data: { confirm: 'Are you sure?' } %>
                      <% else %>
                      <% end %>
                  </div>
              </a>
              
          </div>
        <% end %>
    </div>
</div>

<% if current_account && current_account.id == @shop.seller.account.id %>
  <div class="card">
  <div class="card-header">新增商品</div>
  <div class="card-body">
    <%= form_for Commodity.new, url: commodities_url do |f| %>
      <p>
        <%= f.label :name, "商品名称", class: "labelName" %>
        <%= f.text_field :name, class: "formTextArea" %>
      </p>
      <p>
        <%= f.label :introduction, "商品简介", class: "labelName" %>
        <%= f.text_area :introduction, class: "formTextArea" %>
      </p>
      <p>
        <%= f.label :image, "商品示意图", class: "labelName" %>
        <%= f.file_field :image, accept: 'image/png,image/jpeg,image/jpg' %>
      </p>
      <p>
        <%= f.label :price, "价格", class: "labelName" %>
        <%= f.number_field :price, in: 0.1..10000000000.0, step: 0.1, class: "formTextArea" %>
      </p>
      <div>
        <%= f.hidden_field :shop_id, :value => @shop.id, class: "formTextArea" %>
      </div>
      <p class="labelName">
        选择类别
      </p>
        <div>
          <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
            <%= b.label(:"data-value" => b.value, style:"display: inline; font-size: 17px;") {
              b.check_box(class: "check_box") + b.text } %>
          <% end %>
        </div>

      <p>
        <%= f.submit "新增商品", class: "btn btn-primary", style: "color: gainsboro; margin-top: 1%" %>
      </p>
    <% end %>
  </div>
<% end %>
</div>

<%= link_to '返回', seller_path(@shop.seller), class: 'btn btn-primary', style: "color: gainsboro; width: 10%; margin-top: 1%" %>