config/routes.rb
Rails.application.routes.draw do
  resources :complaints do
    get 'handle'
    post 'do_handle'
  end
  root :to => 'commodities#index'

  resources :sellers do
    resources :shops
  end

  resources :commodities do
    resources :sections do
      resources :comments do
        get 'reply'
        post 'do_reply'
      end
    end
    collection do
      post 'do_filter'
    end
  end

  resources :categories
  resources :admins
  resources :customers do
    resources :orders do
      post 'purchase'
    end
    resources :records
  end
  resources :accounts do
    collection do
      get 'login'
      post 'do_login'
      get 'logout'
      get 'register'
      post 'do_register'
    end
    get 'top_up'
    post 'do_top_up'
    get 'statistic'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_one :admin, dependent: :destroy
  has_one :seller, dependent: :destroy
  has_one :customer, dependent: :destroy
  validates :name, :password, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :account, dependent: :destroy
  has_many :complaints, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :commodities
  has_one_attached :image, dependent: :destroy
  validates :image, attached: true, content_type: [:jpg, :png, :jpeg], size: { less_than: 5.megabytes }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :account
  belongs_to :section
  belongs_to :comment
  has_many :comments
  validates :content, presence: true

  def destroy
    comments.filter { |c| c != self }.each { |c| c.destroy }
    super
  end
end

app/models/commodity.rb
class Commodity < ApplicationRecord
  belongs_to :shop
  has_and_belongs_to_many :categories, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :name, :price, :introduction, presence: true
  validates :image, attached: true, content_type: [:jpg, :png, :jpeg], size: { less_than: 5.megabytes }
  scope :filter_by_categories, -> (cset) {
    reject { |c|
      (c.category_ids.map(&:to_i) & cset.reject(&:blank?).map(&:to_i)).empty?
    }
  }

  def sections
    Section.all.filter { |s| s.commodity == self }
  end

  def sales_volume
    Order.all.filter { |o| o.commodity == self && o.done }.map { |o| o.count }.reduce { |x, y| x + y } || 0
  end
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :customer
  belongs_to :seller
  belongs_to :admin, :optional => true
  validates :content, presence: true

  def is_handled?
    not self.admin.nil?
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :account
  has_many :orders, dependent: :destroy
  has_many :complaints, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :commodity
  belongs_to :customer
  has_one :record, dependent: :destroy
  validates :count, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :order
  has_one :section, dependent: :destroy
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :record
  has_many :comments, dependent: :destroy
  validates :grade, presence: true

  def commodity
    record.order.commodity
  end
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :account
  has_many :complaints, dependent: :destroy
  has_many :shops, dependent: :destroy
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :seller
  has_many :commodities, dependent: :destroy
  validates :name, :introduction, presence: true
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: %i[ show edit update destroy authenticate_handle ]
  before_action :set_handle_complaint, only: %i[ handle do_handle ]
  before_action :authenticate_create, only: [:new, :edit, :create, :update]
  before_action :authenticate_show, only: [:show, :edit, :update]
  before_action :authenticate_handle, only: [:do_handle, :handle]
  before_action :authenticate_check_not_handled, only: [:handle, :do_handle, :edit, :destroy, :update]
  before_action :authenticate_destroy, only: [:destroy]

  def authenticate_create
    redirect_to login_accounts_url, alert: "Must login as customer" unless current_customer?
  end

  def authenticate_show
    redirect_to login_accounts_url, alert: "You have no permission to visit this page" unless current_admin? || (
      current_customer? && current_account.customer == @complaint.customer
    ) || (
      current_seller? && current_account.seller == @complaint.seller
    )
  end

  def authenticate_handle
    redirect_to login_accounts_url, alert: "Must login as ADMIN" unless current_admin?
    index
  end

  def authenticate_check_not_handled
    redirect_to complaints_url, status: :not_acceptable if @complaint.is_handled?
  end

  def authenticate_destroy
    redirect_to complaints_url, status: :not_acceptable unless current_admin? || (
      current_customer? && current_account.customer == @complaint.customer
    )
  end

  def handle
  end

  def do_handle
    respond_to do |format|
      if @complaint.update(complaint_handle_params)
        format.html { redirect_to complaints_url, notice: "成功处理投诉！" }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /complaints or /complaints.json
  def index
    if current_admin?
      @complaints = Complaint.all
    elsif current_seller?
      @complaints = Complaint.all.filter { |c| c.seller == current_account.seller }
    elsif current_customer?
      @complaints = Complaint.all.filter { |c| c.customer == current_account.customer }
    end
  end

  # GET /complaints/1 or /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints or /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: "成功创建投诉！" }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1 or /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: "成功更新投诉！" }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1 or /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: "成功销毁投诉！" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    def set_handle_complaint
      @complaint = Complaint.find(params[:complaint_id])
    end

    # Only allow a list of trusted parameters through.
    def complaint_params
      params.require(:complaint).permit(:customer_id, :seller_id, :content)
    end

    def complaint_handle_params
      params.require(:complaint).permit(:admin_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/complaints/_edit_form.html.erb
<%= form_with(model: complaint, local: true) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% complaint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-dark">当前用户： <%= current_account.name %></div>
  <li class="dropdown-divider "></li>

  <div class="center" style="width: 50%; margin: auto;">
    <div class="field">
      <div class="text-dark labelLine">投诉对象<br>
        <%= form.collection_select(:seller_id, Seller.all, :id, -> (s) { s.account.name }, {}, {:class => "downLine"}) %>
      </div>
    </div>

    <div class="field">
      <%= form.hidden_field :customer_id, :value => complaint.customer.id %>
    </div>

    <div class="field">
      <div class="text-dark labelLine">投诉内容<br>
        <%= form.text_area :content, class:"complaintText"%>
      </div>
    </div>

    <div class="actions">
      <% if complaint.is_handled? %>
        <div class="leftButton"></div>
      <% else %>
        <%= form.submit class: "btn btn-primary leftButton", value: "编辑信息", data: { disable_with: "正在编辑信息" }%>
      <% end %>
      <%= link_to '返回', complaints_path, class: "btn btn-primary rightButton", style: "color: gainsboro; width: 40%;" %>
    </div>
  </div>
<% end %>

app/views/complaints/_form.html.erb
<%= form_with(model: complaint, local: true) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% complaint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-dark">当前用户： <%= current_account.name %></div>
  <li class="dropdown-divider "></li>

  <div class="center" style="width: 50%; margin: auto;">
    <div class="field">
      <div class="text-dark labelLine">投诉对象<br>
        <%= form.collection_select(:seller_id, Seller.all, :id, -> (s) { s.account.name }, {}, {:class => "downLine"}) %>
      </div>
    </div>

    <div class="field">
      <%= form.hidden_field :customer_id, :value => current_account.customer.id %>
    </div>

    <div class="field">
      <div class="text-dark labelLine">投诉内容<br>
        <%= form.text_area :content, class:"complaintText"%>
      </div>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary leftButton", value: "创建投诉", data: { disable_with: "正在创建投诉" }%>
      <%= link_to '返回', complaints_path, class: "btn btn-primary rightButton", style: "color: gainsboro" %>
    </div>

  </div>
<% end %>

app/views/complaints/edit.html.erb
<body class="loginSurface">

<h1 class="text-center">编辑投诉</h1>

<div class="card complaintCard">
  <div class="card-header">投诉信息</div>
  <div class="card-body">
    <%= render 'edit_form', complaint: @complaint %>
  </div>
</div>

</body>

app/views/complaints/handle.html.erb
<body class="loginSurface">

<% if alert %>
  <div class="<%= alert["type"]%>" role="<%= alert["role"] %>" style="left: auto">
    <h4 class="alert-heading" style="text-align: left"><%= alert["id"] %></h4>
  </div>
<% end %>

<% if notice %>
  <div role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<div class="card complaintCard">
  <div class="card-header">诉求信息</div>
  <div class="card-body">
    <p>
      <strong>买家:</strong>
      <%= @complaint.customer.account.name %>
    </p>

    <p>
      <strong>卖家:</strong>
      <%= @complaint.seller.account.name %>
    </p>

    <p>
      <strong>投诉内容:</strong>
      <%= @complaint.content %>
    </p>


    <%= form_with url: complaint_do_handle_url(@complaint) do %>
      <%= fields_for :complaint do |c| %>
        <%= c.hidden_field :admin_id, :value => current_account.admin.id %>
      <% end %>
      <%= submit_tag 'Do it' , style: "color: gainsboro; width: 40%; margin-right: 19%", class: "btn btn-primary", value: "处理诉求", data: { disable_with: "正在处理诉求" }%>
      <%= link_to '返回', complaints_path, class: "btn btn-primary", style: "color: gainsboro; width: 40%;" %>
    <% end %>

  </div>
</div>

</body>

app/views/complaints/index.html.erb
<body class="loginSurface">

<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<h1 class="text-center">所有投诉</h1>

<div class="card text-center" style="">
  <div class="card-body">

    <table class="table table-bordered table-hover table-striped">
      <thead>
        <tr>
          <th>买家</th>
          <th>卖家</th>
          <th>内容</th>
          <th>处理人</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @complaints.each do |complaint| %>
          <tr>
            <td><%= complaint.customer.account.name %></td>
            <td><%= complaint.seller.account.name %></td>
            <td><%= complaint.content %></td>
            <% if complaint.admin %>
              <td><%= complaint.admin.account.name %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <td><%= link_to '查看详情', complaint, style: "color: #1b1e21; background-color: transparent;"%></td>
            <% if current_customer? && complaint.customer == current_account.customer && !complaint.is_handled? %>
              <td><%= link_to '编辑', edit_complaint_path(complaint), style: "color: #1b1e21; background-color: transparent;" %></td>
            <% elsif current_admin? && !complaint.is_handled? %>
              <td><%= link_to '处理', complaint_handle_path(complaint), style: "color: #1b1e21; background-color: transparent;" %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <% if !complaint.is_handled? && (current_customer? || current_admin?) %>
              <td><%= link_to '删除', complaint, method: :delete, data: { confirm: 'Are you sure?' }, style: "color: #1b1e21; background-color: transparent;" %></td>
            <% else %>
              <td>-</td>
            <% end %>
            </tr>
        <% end %>
      </tbody>
    </table>

<br>
  <% if current_customer? %>
    <%= link_to '新建投诉', new_complaint_path, class: "btn btn-primary", style: "color: gainsboro; width: 10%;" %>
  <% end %>
  </div>
</div>

<br>

</body>

app/views/complaints/new.html.erb
<h1 class="text-center">新建投诉</h1>

<div class="card complaintCard">
  <div class="card-header">投诉信息</div>
  <div class="card-body">
    <%= render 'form', complaint: @complaint %>
  </div>
</div>

app/views/complaints/show.html.erb
<body class="loginSurface">

<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<div class="card complaintCard">
  <div class="card-header">投诉信息</div>
  <div class="card-body">
    <p>
      <strong>买家:</strong>
      <%= @complaint.customer.account.name %>
    </p>

    <p style="margin: 5%auto">
      <strong>卖家:</strong>
      <%= @complaint.seller.account.name %>
    </p>

    <p style="margin: 5%auto">
      <strong>投诉内容:</strong>
      <%= @complaint.content %>
    </p>

    <p style="margin: 5%auto">
      <strong>处理人:</strong>
      <%= @complaint.admin.account.name if @complaint.admin %>
    </p>

    <% if @complaint.is_handled? || current_seller?%>
      <div class="leftButton"></div>
    <% else %>
      <%= link_to '修改信息', edit_complaint_path(@complaint), class: "leftButton btn btn-primary", style: "color: gainsboro;"%>
    <% end %>
    <%= link_to '返回', complaints_path, class: "rightButton btn btn-primary", style: "color: gainsboro; width: 40%;" %>
  </div>
</div>