config/routes.rb
Rails.application.routes.draw do
  resources :complaints do
    get 'handle'
    post 'do_handle'
  end
  root :to => 'commodities#index'

  resources :sellers do
    resources :shops
  end

  resources :commodities do
    resources :sections do
      resources :comments do
        get 'reply'
        post 'do_reply'
      end
    end
    collection do
      post 'do_filter'
    end
  end

  resources :categories
  resources :admins
  resources :customers do
    resources :orders do
      post 'purchase'
    end
    resources :records
  end
  resources :accounts do
    collection do
      get 'login'
      post 'do_login'
      get 'logout'
      get 'register'
      post 'do_register'
    end
    get 'top_up'
    post 'do_top_up'
    get 'statistic'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_one :admin, dependent: :destroy
  has_one :seller, dependent: :destroy
  has_one :customer, dependent: :destroy
  validates :name, :password, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :account, dependent: :destroy
  has_many :complaints, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :commodities
  has_one_attached :image, dependent: :destroy
  validates :image, attached: true, content_type: [:jpg, :png, :jpeg], size: { less_than: 5.megabytes }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :account
  belongs_to :section
  belongs_to :comment
  has_many :comments
  validates :content, presence: true

  def destroy
    comments.filter { |c| c != self }.each { |c| c.destroy }
    super
  end
end

app/models/commodity.rb
class Commodity < ApplicationRecord
  belongs_to :shop
  has_and_belongs_to_many :categories, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :name, :price, :introduction, presence: true
  validates :image, attached: true, content_type: [:jpg, :png, :jpeg], size: { less_than: 5.megabytes }
  scope :filter_by_categories, -> (cset) {
    reject { |c|
      (c.category_ids.map(&:to_i) & cset.reject(&:blank?).map(&:to_i)).empty?
    }
  }

  def sections
    Section.all.filter { |s| s.commodity == self }
  end

  def sales_volume
    Order.all.filter { |o| o.commodity == self && o.done }.map { |o| o.count }.reduce { |x, y| x + y } || 0
  end
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :customer
  belongs_to :seller
  belongs_to :admin, :optional => true
  validates :content, presence: true

  def is_handled?
    not self.admin.nil?
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :account
  has_many :orders, dependent: :destroy
  has_many :complaints, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :commodity
  belongs_to :customer
  has_one :record, dependent: :destroy
  validates :count, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :order
  has_one :section, dependent: :destroy
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :record
  has_many :comments, dependent: :destroy
  validates :grade, presence: true

  def commodity
    record.order.commodity
  end
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :account
  has_many :complaints, dependent: :destroy
  has_many :shops, dependent: :destroy
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :seller
  has_many :commodities, dependent: :destroy
  validates :name, :introduction, presence: true
end

app/controllers/commodities_controller.rb
class CommoditiesController < ApplicationController
  before_action :set_commodity, only: %i[ show edit update destroy ]
  before_action :authenticate, except: [:do_filter, :index, :show]

  def authenticate
    redirect_to login_accounts_url, alert: 'Must Login as this commodity\'s owner!' unless current_account &&
      current_account.id == (params[:commodity] && params[:commodity][:shop_id] ?
                               Shop.find(params[:commodity][:shop_id]).seller.account.id :
                               @commodity.shop.seller.account.id)
  end

  def do_filter
    @commodities = Commodity.all
    @commodities = @commodities.filter_by_categories(params[:category_ids]) if params[:category_ids].present?
    flash[:commodity_filter] = @commodities
    flash[:filter_categories] = params[:category_ids].reject(&:blank?).map(&:to_i)
    redirect_to commodities_url
  end

  # GET /commodities or /commodities.json
  def index
    @temp_filter = flash[:commodity_filter]
    @temp_categories = flash[:filter_categories]
    flash.delete(:commodity_filter)
    flash.delete(:filter_categories)
    if @temp_filter
      print @temp_filter
      @commodities = @temp_filter.map { |c| Commodity.all.filter { |cc| cc.id == c["id"] }.first }
      print @commodities
    else
      @commodities = Commodity.all
    end
  end

  # GET /commodities/1 or /commodities/1.json
  def show
  end

  # GET /commodities/new
  def new
    @commodity = Commodity.new
  end

  # GET /commodities/1/edit
  def edit
  end

  # POST /commodities or /commodities.json
  def create
    @commodity = Commodity.new(commodity_params)
    respond_to do |format|
      if @commodity.save
        @commodity.image.attach(params[:commodity][:image])
        format.html { redirect_to @commodity, notice: "成功创建商品！" }
        format.json { render :show, status: :created, location: @commodity }
      else
        format.html { redirect_to seller_shop_url(@commodity.shop.seller, @commodity.shop), notice: "信息填写不完善！" }
        format.json { render json: @commodity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commodities/1 or /commodities/1.json
  def update
    respond_to do |format|
      if @commodity.update(commodity_params)
        if params[:commodity][:image]
          @commodity.image.attach(params[:commodity][:image])
        end
        format.html { redirect_to @commodity, notice: "成功更新商品！" }
        format.json { render :show, status: :ok, location: @commodity }
      else
        format.html { render "commodities/edit", status: :unprocessable_entity }
        format.json { render json: @commodity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commodities/1 or /commodities/1.json
  def destroy
    @commodity.destroy
    respond_to do |format|
      format.html { redirect_to seller_shop_url(@commodity.shop.seller, @commodity.shop), notice: "成功删除商品！" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commodity
      @commodity = Commodity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def commodity_params
      params.require(:commodity).permit(:name, :introduction, :price, :shop_id, :image, category_ids: [])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/commodities/_commodity.html.erb
<div id="commodity_<%= commodity.id %>">
  <p>
    Name: <strong><%= commodity.name %></strong><br/>
    Introduction: <%= commodity.introduction %><br/>
    Price: <%= commodity.price %>
  </p>
  <%= link_to 'Details', commodity %> |
  <% if current_account && current_account.id == commodity.shop.seller.account.id %>
    <%= link_to 'Destroy', commodity, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/commodities/_form.html.erb
<div>
	<%= form_with(model: commodity, local: true) do |form| %>
	  <% if commodity.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(commodity.errors.count, "error") %> prohibited this commodity from being saved:</h2>

		  <ul>
		  <% commodity.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>







	  <div class="center" style="width: 50%; margin: auto;">
		  <div class="field">
		    <div class="text-dark labelLine">商品名称<br> <%= form.text_field :name, require:"", class:"textBoxLine", placeholder: "新名称" %></div>
		  </div>
		  
		  <div class="field">
		    <div class="text-dark labelLine">商品介绍<br> <%= form.text_area :introduction, require:"", class:"textBoxLine", placeholder: "介绍" %></div>
		  </div>
		  
		  <div class="field">
		    <div class="text-dark labelLine">商品单价<br> <%= form.number_field :price, in: 0.1..10000000000.0, step: 0.1, require:"", class:"textBoxLine", placeholder: "" %></div>
		  </div>

      <p class="labelName">
        选择类别
      </p>
      <div class="labelName">
        <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
          <%= b.label(:"data-value" => b.value, style:"display: inline; font-size: 17px;") { b.check_box + b.text } %>
        <% end %>
      </div>

      <% if commodity.image.attached? %>
        <p>
          <image src="<%= url_for commodity.image %>"></image>
        </p>
      <% end %>

			<div class="field">
			  <%= form.label :upload, "更新图片", class: "labelName" %>
			  <%= form.file_field :image, accept: 'image/png,image/jpeg,image/jpg' %>
			</div>

			<div class="actions">
			  <%= form.submit :更新商品信息, class: "btn btn-primary btnCommodity", style: "color: gainsboro" %>
			</div>
	  </div>
	<% end %>
</div>

app/views/commodities/edit.html.erb
<h1 class="text-center">编辑商品信息</h1>
<div class="card accountCard">
  <div class="card-header">商品信息</div>
  <div class="card-body">
    <%= render 'form', commodity: @commodity %>
  </div>
  </div>
</div>
<%= link_to '返回', commodities_path, class:'btn btn-primary btnCommodity', style: "color: gainsboro" %>

app/views/commodities/index.html.erb
<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<!-- 分类筛选功能 -->
<div class="filterBlock">
  <h4 style="margin-left: 1%; margin-top: 1%">条件筛选</h4>
  <%= form_with url: do_filter_commodities_url do |f| %>
    <div style="margin-left: 1%">
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
        <%= b.label(:"data-value" => b.value, style:"display: inline; font-size: 17px;") {
          b.check_box(checked: @temp_categories.nil? ? true : @temp_categories.include?(b.value), class: "check_box") + b.text
        }%>
      <% end %>
    </div>
    <div class="actions" style="text-align:right; margin-right: 1%;">
      <%= f.submit '筛选', class:"btn btn-primary", style:"width: 60px; height: 40px;"%>
    </div>
  <% end %>
</div>

<div class="content">  
  <div class="proRow">
      <% @commodities.each do |commodity| %>
          <div class="proBig">
              <div class="pro">
                  <div class="proImg">
                    <% if commodity.image.attached? %>
                      <image src="<%= url_for commodity.image %>" style="width: 100%"></image>
                    <% end %>
                  </div>
                  <div class="proText">
                      <h5 class="h5Commodity"><%= commodity.name %></h5>
                      <p class = "proIntro"><%= commodity.introduction %></p>
                      <p class = "proPrice"><%= commodity.price %> RMB</p>
                      <p class = "proFrom"><%= commodity.shop.name %></p>
                      <p class = "proCatagory"><%= commodity.categories.collect { |c| c.name }.reduce { |x, y| x + ", " + y } %></p>
                  </div>
              </div>
              <a href="#">
                  <div class="proBtn">
                  	  <%= link_to '查看', commodity, class:'btn btn-primary btnCommodity', style: "color: gainsboro"%>
                      <% if current_account && current_account.id == commodity.shop.seller.account.id %>
                        <%= link_to '编辑', edit_commodity_path(commodity), class:'btn btn-primary btnCommodity', style: "color: gainsboro"%>
                        <%= link_to '删除', commodity, class:'btn btn-primary btnCommodity', style: "color: gainsboro",  method: :delete, data: { confirm: 'Are you sure?' } %>
                      <% else %>
                      <% end %>
                  </div>
              </a>
              
          </div>
        <% end %>
    </div>
</div>

<% if current_account && current_account.role == "Seller" %>
  <%= link_to '我的商店', seller_url(current_account.seller), class:'btn btn-primary btnCommodity', style: "color: gainsboro" %>
<% end %>

app/views/commodities/new.html.erb
<h1>New Commodity</h1>

<%= render 'form', commodity: @commodity %>

<%= link_to 'Back', commodities_path %>

app/views/commodities/show.html.erb
<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<% if alert %>
  <div class="<%= alert["type"]%>" role="<%= alert["role"] %>" style="left: auto">
    <h4 class="alert-heading" style="text-align: left"><%= alert["id"] %></h4>
  </div>
<% end %>

<div>
	<div class="proIntroMargin">
		<div style="text-align: center">
			<% if @commodity.image.attached? %>
			  <image src="<%= url_for @commodity.image %>" style="width: 485px"></image>
			<% end %>
		</div>
		
		<div class="card" style="width: 485px; margin:1% auto;">
		  <div class="card-header" style="font-weight: bold">商品信息</div>
		  <div class="card-body" style="font-weight: bold">
			  <p>商品名称：<%= @commodity.name %></p>
			  <p>商品介绍：<%= @commodity.introduction %></p>
			  <p>商品价格：<%= @commodity.price %> RMB</p>
			  <p>所属商店：<%= @commodity.shop.name %></p>
			  <p>商品类别：<%= @commodity.categories.collect { |c| c.name }.reduce { |x, y| x + ", " + y } %></p>
        <% if current_account && current_account.id == @commodity.shop.seller.account.id %>
          <%= link_to '编辑', edit_commodity_url(@commodity), class:'btn btn-primary btnCommodity', style: "color: gainsboro" %>
        <% end %>
        </div>
		</div>
	</div>
</div>



<!--评论模块-->
<div class="bodyCommodityShow">
<% unless @commodity.sections.empty? %>
<ul id="pn">
	<% @commodity.sections.reject { |s| s.comments.empty?  }.each do |s| %>
    <li class="list0" >
        <div class="contentCommodityShow">
        	<br>
            <p class="text">
              <span class="name">
                <%= s.comments.first.account.name %><label style="display: inline; color: #4e555b;">(<%= s.comments.first.created_at %>)</label>：
              </span>
              <%= s.comments.first.content %>
            </p>
            <div>
            	<%= link_to '查看评论组', commodity_section_url(@commodity, s) %>
            </div>
        </div>
    </li>
    <% end %>
</ul>
<% end %>
</div>

<% if current_customer? %>
  <div class="card accountCard" style="width: 485px">
    <div class="card-header">购买商品</div>
    <div class="card-body text-center">
    <!-- 客户加入购物车 -->
		<%= form_for Order.new, url: customer_orders_url(current_account.customer) do |f| %>
		<div class="field">
		
		  <%= f.label :商品数量, class: "countFont", style: "display: inline" %>
		  <%= f.number_field :count, in: 1..10000000000, step: 1, class: "numberTextArea" %>
		</div>
		<div class="field">
		  <%= f.hidden_field :done, :value => false %>
		</div>
		<div class="field">
		  <%= f.hidden_field :commodity_id, :value => @commodity.id %>
		</div>
		<div class="field">
		  <%= f.hidden_field :customer_id, :value => current_account.customer.id %>
		</div>
		<div class="actions">
		  <%= f.submit "加入购物车", class: "btn btn-primary", style:"margin-top: 1%" %>
		</div>
	  </div>
  </div>
  <% end %>
<% end %>

<div style="width: 485px; margin: auto">
<%= link_to '访问该商品的店铺', seller_shop_path(@commodity.shop.seller, @commodity.shop), class: 'btn btn-primary leftButton', style: "color: gainsboro" %>
<%= link_to '返回', commodities_path, class:'btn btn-primary rightButton', style: "color: gainsboro" %>
</div>