config/routes.rb
Rails.application.routes.draw do
  resources :complaints do
    get 'handle'
    post 'do_handle'
  end
  root :to => 'commodities#index'

  resources :sellers do
    resources :shops
  end

  resources :commodities do
    resources :sections do
      resources :comments do
        get 'reply'
        post 'do_reply'
      end
    end
    collection do
      post 'do_filter'
    end
  end

  resources :categories
  resources :admins
  resources :customers do
    resources :orders do
      post 'purchase'
    end
    resources :records
  end
  resources :accounts do
    collection do
      get 'login'
      post 'do_login'
      get 'logout'
      get 'register'
      post 'do_register'
    end
    get 'top_up'
    post 'do_top_up'
    get 'statistic'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_one :admin, dependent: :destroy
  has_one :seller, dependent: :destroy
  has_one :customer, dependent: :destroy
  validates :name, :password, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  before_action :set_account_for_top_up, only: [:top_up, :do_top_up]
  before_action :authenticate, except: [:statistic, :login, :do_login, :logout, :register, :do_register, :top_up, :do_top_up]
  before_action :authenticate_top_up, only: [:top_up, :do_top_up]
  before_action :authenticate_statistic, only: [:statistic]

  def authenticate
    redirect_to login_accounts_url, alert: "Must Be ADMIN && Login!" unless current_admin?
  end

  def authenticate_top_up
    redirect_to root_url, alert: "Illegal Behavior!" unless current_account &&
      current_account.id == params[:account_id].to_i
  end

  def authenticate_statistic
    redirect_to root_url, alert: "Illegal Behavior!" unless current_admin? || current_seller?
  end

  def statistic
  end

  def login
  end

  def do_login
    account = Account.where(id: params[:id], password: params[:password]).first
    if account
      session[:current_account_id] = account.id
      redirect_to commodities_url, alert: {id: "用户登录成功！", type: "alert alert-success", role: 'alert'}
    else
      redirect_to login_accounts_url, alert: {id: "账户错误或密码错误！", type: "alert alert-danger", role: 'alert'}
    end
  end

  def logout
    session.delete(:current_account_id)
    redirect_to login_accounts_url, alert: {id: "用户注销成功！", type: "alert alert-success", role: 'alert'}
  end

  def register
  end

  def do_register
    name, role, password = params.require([:name, :role, :password])
    @account = Account.new({ name: name, role: role, password: password })
    check_role = /^(Seller|Customer)$/ === @account.role
    if check_role && @account.save
      t = eval(@account.role).new
      t.account_id = @account.id
      @account.update_attribute(:balance, 0)
      t.save
      redirect_to login_accounts_url, alert: {id: "用户注册成功！你的账户ID是" + @account.id.to_s + ".请记住您的ID用于登录", type: "alert alert-success", role: 'alert'}
    else
      redirect_to register_accounts_url, {id: "创建用户失败！", type: "alert alert-danger", role: 'alert'}
    end
  end

  def top_up
  end

  def do_top_up
    delta = top_up_account_params.to_i
    respond_to do |format|
      if delta > 0
        @account.update_attribute(:balance, @account.balance + delta)
        format.html { redirect_to account_top_up_url(@account), alert: {id: "充值成功！", type: "alert alert-success", role: 'alert'} }
        format.json { render :top_up, status: :created, location: account_top_up_url(@account) }
      else
        format.html { render account_top_up_url(@account), alert: { id: "非法充值！", type: "alert alert-danger", role: 'alert' } }
        format.json { render :top_up, status: :unprocessable_entity }
      end
    end
  end

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
    role = @account.role
    check_role = /^(Admin|Seller|Customer)$/ === role

    respond_to do |format|
      if check_role && @account.save
        @account.update_attribute(:balance, 0)
        t = eval(role).new
        t.account_id = @account.id
        t.save
        format.html { redirect_to @account, notice: "账户创建成功！" }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(edit_account_params)
        format.html { redirect_to @account, notice: "用户信息更新成功！" }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "用户账户成功删除！" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def set_account_for_top_up
      @account = Account.find(params[:account_id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :password, :role)
    end

    def edit_account_params
      params.require(:account).permit(:name, :password)
    end

    def top_up_account_params
      params.require(:balance_add)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_create_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-dark">当前用户： <%= current_account.name %></div>
  <li class="dropdown-divider "></li>

  <div class="center" style="width: 50%; margin: auto;">
    <div class="field">
      <div class="text-dark labelLine">用户名<br>
        <%= form.text_field :name, required:"", class:"textBoxLine", placeholder: "您的用户名" %>
      </div>
    </div>

    <div class="field">
      <div class="text-dark labelLine">密码<br>
        <%= form.password_field :password, required:"", class:"textBoxLine", placeholder: "您的密码" %>
      </div>
    </div>

    <div class="field">
      <div class="text-dark labelLine">身份<br>
        <%= form.collection_select(:role, all_roles, :to_s, :to_s, {}, {:class => "downLine"}) %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary leftButton", value: "创建用户", data: { disable_with: "正在创建用户" }%>
      <%= link_to '返回', accounts_path ,class: "btn btn-primary rightButton", style: "color: gainsboro"%>
    </div>
  </div>
<% end %>

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-dark">当前用户： <%= current_account.name %></div>
  <li class="dropdown-divider "></li>

  <div class="center" style="width: 50%; margin: auto;">
    <div class="field">
      <div class="text-dark labelLine">用户名<br>
        <%= form.text_field :name, require:"", class:"textBoxLine", placeholder: "您的用户名" %>
      </div>
    </div>

    <div class="field">
      <div class="text-dark labelLine">新密码<br>
        <%= form.password_field :password, required:"", class:"textBoxLine", placeholder: "您的密码" %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary leftButton", value: "更新信息", data: { disable_with: "正在更新信息" } %>
      <%= link_to '返回', accounts_path ,class: "btn btn-primary rightButton", style: "color: gainsboro"%>
    </div>
  </div>

<% end %>

app/views/accounts/edit.html.erb
<body class="loginSurface" >

<h1 class="text-center">用户信息修改</h1>

<div class="card accountCard">
  <div class="card-header">用户信息</div>
  <div class="card-body">
  <%= render 'form', account: @account %>
  </div>
</div>

</body>

app/views/accounts/index.html.erb
<body class="loginSurface">

<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>


<h1 class="text-center">所有账户</h1>

<div class="card text-center" style="">
<div class="card-body">

  <table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>编号</th>
      <th>用户名</th>
      <th>密码</th>
      <th>角色</th>
      <th>余额</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody style="">
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.id %></td>
        <td><%= account.name %></td>
        <td><%= account.password %></td>
        <td><%= account.role %></td>
        <td><%= account.balance %></td>
        <td><%= link_to '查看详情', account, style: "color: #1b1e21; background-color: transparent;"%></td>
        <td><%= link_to '编辑', edit_account_path(account), style: "color: #1b1e21; background-color: transparent;"%></td>
        <td><%= link_to '删除用户', account, method: :delete, data: { confirm: 'Are you sure?' }, style: "color: #1b1e21; background-color: transparent;"%></td>
      </tr>
    <% end %>
  </tbody>

</table>

  <%= link_to '新建用户', new_account_path, class: "btn btn-primary", style: "color: gainsboro; width: 10%;"%>
</div>
</div>

<br>

</body>

app/views/accounts/login.html.erb
<!DOCTYPE html>

<div class="text-center">
<% if alert %>
  <div class="<%= alert["type"]%>" role="<%= alert["role"] %>" style="left: auto">
    <h4 class="alert-heading" style="text-align: left"><%= alert["id"] %></h4>
  </div>
<% end %>

<%= form_with url: do_login_accounts_path do %>
  <div class="center-in-center">
  <%= image_tag("brand.jpeg", class:"mb-4 brandPhoto") %>
  <h1 class="h3 mb-3 font-weight-normal">欢迎来到天上优购</h1>
  <label for="inputAccount" class="sr-only">Account ID</label>
  <label for="id"></label>
  <input type="text" name="id" id="id" class="form-control" placeholder="账户编号" required autofocus size="5" style="width: 20%; margin:1% auto">
  <label for="inputPassword" class="sr-only">Password</label>
  <label for="password"></label>
  <input type="password" name="password" id="password" class="form-control" placeholder="密码" required style="width: 20%; margin:1% auto">

  <button type="submit" name="commit" value="LOGIN" data-disable-with="正在登录" class="btn btn-primary loginBox" style="color: gainsboro">登录</button>
  <%= link_to '注册', register_accounts_url, class:'btn btn-primary loginBox', style: "color: gainsboro"%>
  </div>
<% end %>

</div>

</div>

app/views/accounts/new.html.erb
<body class="loginSurface" >

<h1 class="text-center">新用户</h1>

<div class="card accountCard">
  <div class="card-header">用户信息</div>
  <div class="card-body">
    <%= render 'create_form', account: @account %>
  </div>
  </div>
</div>

</body>

app/views/accounts/register.html.erb
<% if alert %>
  <div class="<%= alert["type"]%>" role="<%= alert["role"] %>" style="left: auto">
    <h4 class="alert-heading" style="text-align: left"><%= alert["id"] %></h4>
  </div>
<% end %>
<h1 class="text-center">注册用户</h1>

<div class="card accountCard">
  <div class="card-header">用户注册</div>
  <div class="card-body">
  <% unless current_account %>
    <%= form_with url: do_register_accounts_path do %>
      <div class="center" style="width: 50%; margin: auto;">
      <div class="field">
        <div class="text-dark labelLine">用户名<br> <%= text_field_tag :name, "" , class: "textBoxLine", placeholder: "您的用户名", required:""%></div>
      </div>
      <div class="field">
        <div class="text-dark labelLine">角色<br> <%= collection_select(nil, :role, roles, :to_s, :to_s, {}, {:class => "downLine"}) %></div>
      </div>
      <div class="field">
        <div class="text-dark labelLine">密码<br> <%= password_field_tag :password, "", required: "", class: "passwordLine" %></div>
      </div>
      <%= submit_tag 'Register' , value: "注册", class: "btn btn-primary leftButton", data: { disable_with: "正在注册" }%>
      <%= link_to '返回', login_accounts_url, class: "btn btn-primary rightButton", style: "color: gainsboro" %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/accounts/show.html.erb
<body class="loginSurface">

<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<div class="card accountCard">
  <div class="card-header">用户信息</div>
  <div class="card-body">
    <p>
      <strong>用户名：</strong>
      <%= @account.name %>
    </p>

    <p style="margin: 5%auto">
      <strong>密码：</strong>
      <%= @account.password %>
    </p>

    <p style="margin: 5%auto">
      <strong>角色：</strong>
      <%= @account.role %>
    </p>

    <p style="margin: 5%auto">
      <strong>余额：</strong>
      <%= @account.balance %>
    </p>

    <%= link_to '修改信息', edit_account_path(@account), class: "btn btn-primary leftButton", style: "color: gainsboro"%>
    <%= link_to '返回', accounts_path, class: "btn btn-primary rightButton", style: "color: gainsboro" %>

  </div>
</div>


</body>

app/views/accounts/statistic.html.erb
<h1 style="text-align: center">销售数据统计</h1>

<%= javascript_include_tag 'statistics', 'data-turbolinks-track': 'reload', 'data-turbolinks-eval': false %>

<% if current_seller? %>
  <% commodities = Commodity.all.filter { |c| c.shop.seller.account == current_account } %>
<% else %>
  <% commodities = Commodity.all %>
<% end %>

<div style="text-align: center">
  <svg id="app"></svg>
</div>
<%= javascript_tag do %>
  show_data(<%= raw commodities.map { |c| c.sales_volume }.as_json %>,<%= raw commodities.map { |c| c.name + "@" + c.shop.name }.as_json %>)
<% end %>

app/views/accounts/top_up.html.erb
<% if notice %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
        <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </small>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<% if alert %>
  <div id="toast1" role="alert" aria-live="assertive" aria-atomic="true" class="toast">
    <div class="toast-header">
      <strong class="mr-auto">提醒</strong>
      <small>
      <button id="notice1" type="button" class="ml-2 mb-1 toastButton" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </small>
    </div>
    <div class="toast-body">
      <%= alert["id"] %>
    </div>
  </div>
<% end %>

<h1 class="text-center">开始充值</h1>
<div class="card accountCard">
  <div class="card-header">充值信息</div>
  <div class="card-body">
    <div class="text-dark">当前余额：<%= @account.balance %></div>
    <li class="dropdown-divider "></li>
    <%= form_with url: account_do_top_up_path(@account) do %>
        <div class="text-dark labelLine">充值金额<br></div>
        <div class="labelLine">
          <%= number_field_tag :balance_add, 1, { min: 1, max: 10000, required:"", class:"textBoxLine" }%>
        </div>
        <%= submit_tag '确认充值', class:"leftButton btn btn-primary", style:"color: gainsboro"%>
        <%= link_to '返回主页', root_url, class: "btn btn-primary rightButton", style: "color: gainsboro" %>
    <% end %>
  </div>
</div>